# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vasa < Formula
  desc "CLI for the Vasa data platform"
  homepage "https://tryvasa.com"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nordlake/homebrew-tap/releases/download/v0.1.0/vasa_darwin_amd64.tar.gz"
      sha256 "dfc7f5410c50a5a184f4b65e077f2549a305048ff22a3ed92f6818a42fa44b29"

      define_method(:install) do
        bin.install "vasa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nordlake/homebrew-tap/releases/download/v0.1.0/vasa_darwin_arm64.tar.gz"
      sha256 "85d2a378175c7cb959f10c631378423b45d0cb232a5f3f1a72c7ccd47ce60e28"

      define_method(:install) do
        bin.install "vasa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nordlake/homebrew-tap/releases/download/v0.1.0/vasa_linux_amd64.tar.gz"
      sha256 "d1ee92863ed955ee04b67e928b9a0d562466fe4ef57914a6013ede71d9fc072d"
      define_method(:install) do
        bin.install "vasa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nordlake/homebrew-tap/releases/download/v0.1.0/vasa_linux_arm64.tar.gz"
      sha256 "5a6efbee0d7201ae34cbf57b2ebeeb0e6e7338ad09e39c3524c4c3d735e20924"
      define_method(:install) do
        bin.install "vasa"
      end
    end
  end

  test do
    system "#{bin}/vasa", "version"
  end
end
